# Eventually I will remove dependencies from the other config files but a store in here for the calls and 1 file is the goal
server.host=127.0.0.1
server.port=9090
client.host=127.0.0.1
client.port=8080
quic.server.host=0.0.0.0
quic.server.port=4433
quic.client.host=127.0.0.1